// รายการภาพคู่มือ: id = ชื่อไฟล์ใน admin/public/manual/<id>.webp · marks = วงเลขทับตำแหน่งจริงของ element
const hideDemo = page => page.evaluate(() => {
  // กล่อง "บัญชีสำหรับ Demo (DEV only)" มี username จริง — ลบทิ้งก่อนถ่าย (ลบเฉพาะบล็อกที่ไม่มี input)
  const label = [...document.querySelectorAll('*')].filter(e => e.children.length === 0 && e.textContent.includes('DEV only'))[0]
  let el = label
  while (el && el.parentElement && !el.parentElement.querySelector('input')) el = el.parentElement
  if (el) el.remove()
})

module.exports = [
  // ── เริ่มต้นใช้งาน ──
  { id: 'login', path: 'login', w: 1440, h: 900, clip: { x: 790, y: 200, width: 540, height: 470 },
    setup: async (page, { sleep }) => {
      await page.type('input[placeholder="username"]', 'demo.admin')
      await hideDemo(page)
      await page.type('input[type=password]', 'password123')
      await page.evaluate(() => { const i = document.querySelector('input[type=password]'); i.blur() })
    },
    marks: [
      { selector: 'input[placeholder="username"]', n: 1, side: 'l' },
      { selector: 'input[type=password]', n: 2, side: 'l' },
      { text: 'จดจำฉันไว้', tag: 'label, span', n: 3, side: 'l' },
      { text: 'ลืมรหัสผ่าน', tag: 'button, a', n: 4, side: 'tr' },
      { selector: 'button[type=submit]', n: 5, side: 'l' },
    ] },
  { id: 'dashboard', path: 'dashboard',
    marks: [
      { text: 'วันนี้', tag: 'button', n: 1 },
      { text: 'มาสาย (คน)', tag: 'div, button, span', n: 2, nth: 0, card: true },
      { text: 'ใบลา รออนุมัติ', tag: 'button, div', n: 3, card: true },
      { text: 'เข้างานปกติ', tag: 'button', n: 4, card: true },
      { text: 'รายชื่อวันนี้', tag: 'span', n: 5, pad: 8, side: 'tr' },
    ] },
  { id: 'navigation', path: 'dashboard',
    marks: [
      { text: 'ภาพรวม', tag: 'a, button', within: 'aside, nav', n: 1 },
      { text: 'พนักงาน', tag: 'a, button', within: 'aside, nav', n: 2, nth: 0 },
      { text: 'ผู้ดูแลระบบ (ตัวอย่าง)', tag: 'span', n: 3, side: 'l' },
      { text: 'ออกจากระบบ', tag: 'a, button, span', n: 4 },
    ] },

  // ── พนักงาน และ สาขา ──
  { id: 'employee-list', path: 'employee',
    marks: [
      { text: 'เพิ่มพนักงาน', tag: 'button', n: 1 },
      { selector: 'select', nth: 0, n: 2 },
      { selector: 'input[placeholder*="ค้นหา"]', n: 3 },
      { text: 'Export CSV', tag: 'button', n: 4 },
      { text: 'ผูกแล้ว', tag: 'span', n: 5, nth: 0 },
      { selector: 'button:has(svg.lucide-pencil)', n: 6 },
    ] },
  { id: 'branch-list', path: 'branch',
    marks: [
      { text: 'เพิ่มสาขา', tag: 'button', n: 1 },
      { text: 'สาขาสุขุมวิท', tag: 'div, span, h3, h4', n: 2, card: true, pad: 2, side: 'l' },
      { text: 'เพิ่มกะ', tag: 'button', n: 3, nth: 0 },
      { text: 'QR', tag: 'button', n: 4, nth: 0 },
      { text: 'แก้ไข', tag: 'button', n: 5, nth: 0 },
      { text: 'ลบ', tag: 'button', n: 6, nth: 0 },
    ] },

  // ── การลา และ วันหยุด ──
  { id: 'leave-requests', path: 'leave',
    marks: [
      { text: 'รอพิจารณา', tag: 'button', n: 1, nth: 0 },
      { text: 'สร้างวันลา', tag: 'button', n: 2 },
      { text: 'ประเภทการลา', tag: 'button', n: 3 },
      { selector: 'input[placeholder*="ค้นหา"]', n: 4 },
      { text: 'LV-2569-0102', tag: 'td, span', n: 5 },
    ] },
  { id: 'attendance-today', path: 'shift',
    marks: [
      { text: 'ยังไม่เช็ค', exact: true, tag: 'div', n: 1, card: true },
      { selector: 'input[type=date]', n: 2, side: 'l' },
      { selector: 'input[placeholder*="ค้นหาชื่อ"]', n: 3, side: 'l' },
      { text: 'รายงานการเช็คอิน', tag: 'a, button', n: 4 },
      { selector: 'button:has(svg.lucide-pencil)', n: 5, nth: 0 },
    ] },

  // ── modals / แท็บ ──
  { id: 'employee-add', path: 'employee',
    setup: async (p, { clickText, sleep }) => { await clickText(p, 'เพิ่มพนักงาน', 'button'); await sleep(900)
      await p.type('input[placeholder="ชื่อจริง"]', 'วิภา'); await p.type('input[placeholder="นามสกุล"]', 'ตัวอย่างดี'); await p.type('input[placeholder*="บาส"]', 'วิ'); await p.type('input[placeholder="08XXXXXXXX"]', '0812345678') },
    marks: [
      { text: 'ข้อมูลส่วนตัว', tag: 'div, span', n: 1, pad: 14, nth: 0, side: 'l' },
      { selector: 'input[placeholder="ชื่อจริง"]', n: 2 },
      { selector: 'input[placeholder="นามสกุล"]', n: 3, side: 'tr' },
      { selector: 'input[placeholder*="บาส"]', n: 4, side: 'l' },
      { selector: 'input[placeholder="08XXXXXXXX"]', n: 5 },
      { text: 'ข้อมูลเพิ่มเติม', tag: 'button', n: 6, side: 'l' },
      { text: 'ถัดไป', tag: 'button', n: 7 },
    ] },
  { id: 'branch-add', path: 'branch',
    setup: async (p, { clickText, sleep }) => { await clickText(p, 'เพิ่มสาขา', 'button'); await sleep(900)
      await p.type('input[placeholder*="สำนักงานใหญ่"]', 'สาขาลาดพร้าว'); await p.type('input[placeholder*="BR001"]', 'LPR'); await p.type('textarea', '99 ถนนลาดพร้าว กรุงเทพฯ'); await sleep(300) },
    marks: [
      { text: 'ข้อมูลสาขา', tag: 'div, span', n: 1, nth: 0, pad: 12, side: 'l' },
      { selector: 'input[placeholder*="สำนักงานใหญ่"]', n: 2, side: 'l' },
      { selector: 'input[placeholder*="BR001"]', n: 3, side: 'l' },
      { selector: 'textarea', n: 4, side: 'l' },
      { text: 'ใช้ค่าจากกลุ่ม', tag: 'button', n: 5, nth: 0, side: 'l' },
      { text: 'ถัดไป', tag: 'button', n: 6 },
    ] },
  { id: 'leave-create', path: 'leave',
    setup: async (p, { clickText, sleep }) => { await clickText(p, 'สร้างวันลา', 'button'); await sleep(900)
      await clickText(p, 'เลือกพนักงาน —', 'div, button, span'); await sleep(600); await clickText(p, 'วิภา สุขใจ', 'div, li, button, span'); await sleep(700)
      await p.evaluate(() => { const set = (el, v) => { Object.getOwnPropertyDescriptor(HTMLInputElement.prototype, 'value').set.call(el, v); el.dispatchEvent(new Event('input', { bubbles: true })); el.dispatchEvent(new Event('change', { bubbles: true })) }
        const d = [...document.querySelectorAll('input[type=date]')]; const t = new Date(Date.now() + 86400000 * 3).toISOString().slice(0, 10); d.forEach(x => set(x, t)) })
      await p.type('input[placeholder*="เหตุผล"]', 'ไปพบแพทย์'); await sleep(400) },
    marks: [
      { text: 'วิภา สุขใจ', tag: 'div, span', n: 1, side: 'l', pad: 8 },
      { text: 'ลาป่วย', tag: 'button', n: 2, nth: 0, side: 'l' },
      { text: 'เต็มวัน', tag: 'button', n: 3, side: 'l' },
      { selector: 'input[type=date]', n: 4, nth: 0, side: 'l' },
      { selector: 'input[type=date]', n: 5, nth: 1 },
      { selector: 'input[placeholder*="เหตุผล"]', n: 6, side: 'l' },
      { text: 'บันทึก', tag: 'button', n: 7 },
    ] },
  { id: 'weekly-off-open', path: 'leave', setup: async (p, { clickText, sleep }) => { await clickText(p, 'จองวันหยุดประจำเดือน', 'button, a, div'); await sleep(1200) },
    marks: [
      { text: 'ตุลาคม 2569', exact: true, tag: 'span, div, button', n: 1, nth: 0, side: 'l' },
      { text: 'เปิด/ปิดการจอง', tag: 'button', n: 2 },
      { text: 'เปิดรับจอง', exact: true, tag: 'span, div', n: 3, nth: 0, up: 1, side: 'l' },
      { text: 'ดูรายการจอง (5)', tag: 'button', n: 4 },
      { text: 'รายการคำขอ', tag: 'button', n: 5 },
    ] },
  { id: 'weekly-off-requests', path: 'leave', setup: async (p, { clickText, sleep }) => { await clickText(p, 'จองวันหยุดประจำเดือน', 'button, a, div'); await sleep(900); await clickText(p, 'รายการคำขอ', 'button'); await sleep(1200) },
    marks: [
      { text: 'ตุลาคม 2569', exact: true, tag: 'span, div', n: 1, nth: 0, side: 'l' },
      { text: 'รายการคำขอ', tag: 'button', n: 2 },
      { text: 'อนุมัติทั้งหมด (3)', tag: 'button', n: 3 },
      { text: 'เพิ่มวันหยุด', tag: 'button', n: 4 },
      { text: 'รอพิจารณา', tag: 'button', n: 5, nth: 0 },
      { selector: 'input[placeholder*="ค้นหาชื่อ"]', n: 6 },
      { text: 'ให้จองใหม่ทั้งเดือน', tag: 'button', n: 7, nth: 0 },
    ] },
  { id: 'team-calendar', path: 'leave', setup: async (p, { clickText, sleep }) => { await clickText(p, 'ปฏิทินรวม', 'button, a, div'); await sleep(1500) },
    marks: [
      { text: 'วันหยุดพิเศษ', tag: 'div', n: 1, card: true },
      { selector: 'select', n: 2, nth: 0 },
      { text: 'ลงวันหยุดรายคน', tag: 'button', n: 3 },
      { text: 'ลงวันหยุดหลายคน', tag: 'button', n: 4 },
      { text: 'Excel', tag: 'button', n: 5 },
      { text: 'ตุลาคม 2569', exact: true, tag: 'span, div', n: 6, nth: 0, side: 'l' },
    ] },
  { id: 'attendance-manual', path: 'shift',
    setup: async (p, { clickText, sleep }) => { await clickText(p, '+ ลงบันทึก', 'button'); await sleep(1000)
      await clickText(p, 'กะเช้า', 'button'); await sleep(300)
      await p.evaluate(() => { const set = (el, v) => { Object.getOwnPropertyDescriptor(HTMLInputElement.prototype, 'value').set.call(el, v); el.dispatchEvent(new Event('input', { bubbles: true })); el.dispatchEvent(new Event('change', { bubbles: true })) }
        const t = [...document.querySelectorAll('input[type=time]')]; if (t[0]) set(t[0], '09:05') })
      await p.type('textarea', 'ลืมเช็คอิน เครื่องสแกนเสีย'); await sleep(400) },
    marks: [
      { text: 'มาทำงาน', tag: 'button', n: 1 },
      { text: 'กะเช้า', tag: 'button', n: 2 },
      { selector: 'input[type=time]', n: 3, nth: 0, side: 'l' },
      { selector: 'select', n: 4, pick: 'last', side: 'tr' },
      { selector: 'textarea', n: 5, side: 'l' },
      { text: 'ลงเวลา', tag: 'button', n: 6, pick: 'last' },
    ] },

  // ── รอบ 2 ──
  { id: 'employee-info', path: 'employee/e1?tab=info', w: 1440, h: 1500,
    marks: [
      { text: 'ข้อมูลส่วนตัว', tag: 'button', n: 1, pad: 6 },
      { text: 'เลขบัตรประชาชน', tag: 'div', n: 2, up: 1 },
      { text: 'วันเกิด', tag: 'div', exact: true, n: 3, up: 1 },
      { text: 'เบอร์สำรอง', tag: 'div', n: 4, up: 1 },
      { text: 'ที่อยู่ตามบัตรประชาชน', tag: 'div, h3, span', n: 5, card: true },
      { text: 'ผู้ติดต่อฉุกเฉิน', tag: 'div, h3, span', n: 6, card: true },
      { text: 'Reset LINE', tag: 'button', n: 7 },
    ] },
  { id: 'employee-add-extra', path: 'employee', w: 1440, h: 1150,
    setup: async (p, { clickText, sleep }) => { await clickText(p, 'เพิ่มพนักงาน', 'button'); await sleep(900); await clickText(p, 'ข้อมูลเพิ่มเติม', 'button'); await sleep(800) },
    marks: [
      { text: 'ซ่อนข้อมูลเพิ่มเติม', tag: 'button', n: 1 },
      { text: 'เลขบัตรประชาชน', tag: 'label, div', exact: true, n: 2, up: 1, side: 'l' },
      { text: 'เลขประกันสังคม', tag: 'label, div', exact: true, n: 3, up: 1 },
      { text: 'วันเกิด', tag: 'label, div', exact: true, n: 4, up: 1, side: 'l' },
      { text: 'หมู่เลือด', tag: 'label, div', exact: true, n: 5, up: 1 },
      { text: 'เบอร์ติดต่อสำรอง', tag: 'label, div', exact: true, n: 6, up: 1, side: 'l' },
    ] },
  { id: 'employee-tab-policy', path: 'employee?tab=policy',
    marks: [
      { text: 'ทั้งหมด 12', tag: 'span, div, button', n: 1 },
      { selector: 'select', nth: 0, n: 2 },
      { selector: 'input[placeholder*="ค้นหา"]', n: 3 },
      { text: 'CSV', tag: 'button', n: 4 },
      { selector: 'tbody select, table select', nth: 0, n: 5 },
      { selector: 'tbody select, table select', nth: 1, n: 6 },
      { selector: 'tbody select, table select', nth: 2, n: 7, side: 'tr' },
    ] },
  { id: 'employee-tab-groups', path: 'employee?tab=groups',
    marks: [
      { text: 'เพิ่มกลุ่ม', tag: 'button', n: 1 },
      { text: 'กลุ่มบริษัทตัวอย่าง', tag: 'div, span', n: 2, card: true, side: 'l' },
      { text: 'จองวันหยุดได้', tag: 'span', n: 3 },
      { text: 'ดูผังองค์กร', tag: 'button', n: 4 },
      { selector: 'button:has(svg.lucide-pencil)', nth: 0, n: 5 },
      { text: 'สาขาสุขุมวิท', tag: 'span', n: 6 },
    ] },
  { id: 'employee-tab-org', path: 'employee?tab=org',
    marks: [
      { text: 'ลาก-วางจัดพนักงาน', tag: 'button', n: 1 },
      { text: 'ฝ่าย', exact: true, tag: 'button, span', n: 2, nth: 0 },
      { text: 'แผนก', exact: true, tag: 'button, span', n: 3, nth: 0 },
      { text: 'ตำแหน่ง', exact: true, tag: 'button, span', n: 4, nth: 0 },
      { text: 'ฝ่ายปฏิบัติการ', tag: 'div, span', n: 5, card: true },
    ] },
  { id: 'employee-tab-status', path: 'employee?tab=status',
    marks: [
      { text: 'เพิ่มสถานะ', tag: 'button', n: 1 },
      { text: 'พนักงานประจำ', tag: 'div, span', n: 2, card: false, nth: 0, side: 'l', pad: 6 },
      { text: '5 วัน/เดือน', tag: 'span', n: 3 },
      { text: 'โควต้า = เสาร์-อาทิตย์ของเดือน', tag: 'span', n: 4 },
      { selector: 'button:has(svg.lucide-pencil)', nth: 0, n: 5 },
      { selector: 'button:has(svg.lucide-trash-2)', nth: 0, n: 6 },
    ] },
  { id: 'leave-tab-vacation', path: 'leave', setup: async (p, { clickText, sleep }) => { await clickText(p, 'นโยบายพักร้อน', 'button, a, div'); await sleep(1500) },
    marks: [
      { text: 'รวมนโยบายพักร้อนตามอายุงาน', tag: 'div, p, span', n: 1, card: true },
      { text: 'ไม่จำกัด (ยื่นย้อนหลังได้เท่าไหร่ก็ได้)', tag: 'div, span', n: 2, up: 1, side: 'l' },
      { text: 'ให้พนักงานยื่นลาออกเองผ่าน LINE ได้', tag: 'div, span', n: 3, up: 1, side: 'l' },
      { text: 'บันทึก', tag: 'button', n: 4, nth: 0 },
      { text: 'สูตรพักร้อนตามอายุงาน (ต่อตำแหน่ง)', tag: 'div, h3, span', n: 5, pad: 8 },
    ] },
  { id: 'leave-tab-holiday', path: 'leave', setup: async (p, { clickText, sleep }) => { await clickText(p, 'วันหยุดนักขัตฤกษ์', 'button, a, div'); await sleep(1500) },
    marks: [
      { text: 'นำเข้าวันหยุดไทย', tag: 'button', n: 1 },
      { text: 'เพิ่มวันหยุด', tag: 'button', n: 2 },
      { text: '2026', exact: true, tag: 'span, div', n: 3, side: 'l' },
      { text: 'นักขัตฤกษ์ 4', tag: 'span', n: 4 },
      { text: 'มกราคม', exact: true, tag: 'div, span', n: 5, card: true, side: 'l' },
      { text: 'รายการวันหยุด 2026', tag: 'div, span, h3', n: 6, card: true },
    ] },
  { id: 'leave-tab-quota', path: 'leave', setup: async (p, { clickText, sleep }) => { await clickText(p, 'โควต้า', 'button, a, div'); await sleep(1500) },
    marks: [
      { text: 'เกินโควต้า', tag: 'div, span', n: 1, card: true },
      { text: 'นโยบายพักร้อนตามอายุงาน', tag: 'a, button', n: 2 },
      { text: 'โควต้า Default', tag: 'button', n: 3 },
      { text: 'ใช้กับพนักงานทั้งหมด', tag: 'button', n: 4 },
      { selector: 'input[placeholder*="ค้นหา"]', n: 5, side: 'l' },
      { text: 'แก้ไขแบบตาราง', tag: 'button', n: 6 },
    ] },
  { id: 'ot', path: 'ot',
    marks: [
      { text: 'รายงานพนักงาน (OT)', tag: 'a, button', n: 1 },
      { text: 'Export', tag: 'button', n: 2 },
      { text: 'รวมจ่าย OT', tag: 'button', n: 3 },
      { text: '+ เพิ่ม OT', tag: 'button', n: 4 },
      { text: 'รอพิจารณา', exact: true, tag: 'div, span', n: 5, card: true },
      { selector: 'input[placeholder*="ค้นหา"]', n: 6, side: 'l' },
      { text: 'อนุมัติ', exact: true, tag: 'button', n: 7 },
      { text: 'จ่าย OT', tag: 'button', n: 8, nth: 0 },
    ] },
  { id: 'resignations', path: 'resignations',
    marks: [
      { selector: 'input[placeholder*="ค้นหา"]', n: 1, side: 'l' },
      { selector: 'select', n: 2, nth: 0 },
      { text: 'รอพิจารณา', exact: true, tag: 'span, div', n: 3, nth: 0 },
      { selector: 'button:has(svg.lucide-check)', n: 4, nth: 0 },
      { selector: 'button:has(svg.lucide-x)', n: 5, nth: 0 },
      { text: 'รายงานผู้บริหาร', tag: 'a, button', n: 6 },
    ] },
  { id: 'document-requests', path: 'document-requests',
    marks: [
      { text: 'เพิ่มคำขอ', tag: 'button', n: 1 },
      { text: 'สรุปเงินเดือน/สลิป', tag: 'button, a', n: 2 },
      { selector: 'select', n: 3, nth: 0 },
      { selector: 'input[placeholder*="ค้นหา"]', n: 4, side: 'l' },
      { selector: 'button[title="สร้างในระบบ"]', n: 5, nth: 0 },
      { selector: 'button[title="แนบไฟล์ + เสร็จ"]', n: 6, nth: 0 },
      { selector: 'button[title="ปฏิเสธ"]', n: 7, nth: 0, side: 'tr' },
    ] },
  { id: 'announcement', path: 'announcement', w: 1440, h: 1000,
    setup: async (p, { sleep }) => { await p.type('input[placeholder*="แจ้งหยุด"]', 'แจ้งหยุดเนื่องในวันปิยมหาราช'); await p.type('textarea', 'บริษัทขอแจ้งหยุดทำการวันศุกร์ที่ 23 ตุลาคม เปิดทำการตามปกติวันจันทร์ที่ 26 ตุลาคม'); await sleep(500) },
    marks: [
      { text: 'ใช้เทมเพลต', tag: 'select', n: 1 },
      { text: 'จัดการ Template', tag: 'button', n: 2 },
      { selector: 'input[placeholder*="แจ้งหยุด"]', n: 3, side: 'l' },
      { selector: 'textarea', n: 4, side: 'l' },
      { text: 'ทุกคน', exact: true, tag: 'div', n: 5, up: 1 },
      { text: 'ตัวอย่างที่พนักงานจะเห็นใน LINE', tag: 'div, span', n: 6, card: true },
      { text: 'ส่งประกาศ', exact: true, tag: 'button', n: 7 },
      { text: 'ใช้ซ้ำ', tag: 'button', n: 8, nth: 0 },
    ] },

  // ── รอบ 3 ──
  { id: 'offsite', path: 'offsite',
    marks: [
      { text: 'รายงานการเช็คอิน', tag: 'a, button', n: 1 },
      { text: 'Export', tag: 'button', n: 2 },
      { text: 'เพิ่มรายการ', tag: 'button', n: 3 },
      { text: 'กำลังอยู่นอกสถานที่', tag: 'div, span', n: 4, card: true },
      { selector: 'select', nth: 0, n: 5 },
      { text: 'กำลังนอกสถานที่', exact: true, tag: 'span', n: 6 },
      { selector: 'button:has(svg.lucide-pencil)', nth: 0, n: 7 },
      { selector: 'button:has(svg.lucide-trash-2)', nth: 0, n: 8, side: 'tr' },
    ] },
  { id: 'offsite-add', path: 'offsite', setup: async (p, { clickText, sleep }) => { await clickText(p, 'เพิ่มรายการ', 'button'); await sleep(900) },
    marks: [
      { text: 'เลือกพนักงาน', tag: 'div, button, span, select', n: 1, side: 'l' },
      { selector: 'input[type=date]', n: 2, side: 'l' },
      { selector: 'input[type=time]', n: 3, side: 'tr' },
      { selector: 'input[placeholder*="บริษัท ABC"]', n: 4, side: 'l' },
      { text: 'ยังไม่เช็คเอาต์', tag: 'label, span', n: 5 },
      { selector: 'textarea', n: 6, side: 'l' },
      { text: 'บันทึก', exact: true, tag: 'button', n: 7 },
    ] },
  { id: 'master-data', path: 'master-data',
    marks: [
      { selector: 'input[placeholder*="ค้นหา"]', n: 1, side: 'l' },
      { selector: 'select', nth: 0, n: 2 },
      { text: 'Export', tag: 'button', n: 3 },
      { text: '12 / 12 คน', tag: 'span, div', n: 4 },
      { text: 'สมชาย ใจดี', tag: 'span, a, div', n: 5, pad: 4 },
      { text: 'สาขารอง', tag: 'th, div, span', n: 6 },
    ] },
  { id: 'settings-general', path: 'settings',
    marks: [
      { text: 'ข้อมูลบริษัท & แบรนด์', tag: 'div, h3, span', n: 1, pad: 10, side: 'l' },
      { selector: 'input', nth: 0, n: 2, side: 'l' },
      { text: 'แนบไฟล์', tag: 'button', n: 3 },
      { selector: 'input[placeholder="#244B83"], input[value="#244B83"]', n: 4 },
      { text: 'ผู้ลงนามท้ายเอกสาร HR', tag: 'div, h4, span', n: 5, pad: 6, side: 'l' },
      { text: 'บันทึก', exact: true, tag: 'button', n: 6 },
      { text: 'เกณฑ์การสาย & ค่าปรับ', tag: 'div, span', n: 7, up: 1 },
    ] },
  { id: 'settings-users', path: 'settings', setup: async (p, { clickText, sleep }) => { await clickText(p, 'ผู้ใช้งาน', 'button'); await sleep(1200) },
    marks: [
      { text: 'รหัสผ่านของฉัน', tag: 'div, h3, span', n: 1, card: true },
      { text: 'เพิ่มผู้ใช้งาน', tag: 'button', n: 2 },
      { text: 'ผู้ดูแลระบบ', exact: true, tag: 'span, div', n: 3, nth: 1 },
      { selector: 'button:has(svg.lucide-shield-check), button:has(svg.lucide-shield)', n: 4, nth: 0 },
      { selector: 'button:has(svg.lucide-pencil)', n: 5, nth: 0 },
      { selector: 'button:has(svg.lucide-trash-2)', n: 6, nth: 0, side: 'tr' },
    ] },
  { id: 'settings-notify', path: 'settings', setup: async (p, { clickText, sleep }) => { await clickText(p, 'การแจ้งเตือน', 'button'); await sleep(1200) },
    marks: [
      { text: 'การแจ้งเตือน LINE ไปแอดมิน', tag: 'div, h3, span', n: 1, pad: 8, side: 'l' },
      { text: 'ใบลารออนุมัติ', exact: true, tag: 'div, span', n: 2, up: 1, side: 'l' },
      { text: 'จัดการรายคน', tag: 'button', n: 3, nth: 0 },
      { text: 'ใช้สิทธิ์รายคนร่วมกับ', tag: 'div, span', n: 4, nth: 0, pad: 6 },
    ] },
  { id: 'settings-features', path: 'settings', setup: async (p, { clickText, sleep }) => { await clickText(p, 'ฟีเจอร์', 'button'); await sleep(1200) },
    marks: [
      { text: 'บังคับใช้จริงแล้ว', tag: 'div, h3, span', n: 1, pad: 8, side: 'l' },
      { text: 'จัดการวันลา', exact: true, tag: 'div, span', n: 2, up: 2, side: 'l' },
      { text: 'โควต้าวันลา', exact: true, tag: 'div, span', n: 3, up: 2, side: 'l' },
    ] },
  { id: 'report-checkin', path: 'report',
    marks: [
      { text: 'ปฏิทิน', exact: true, tag: 'button', n: 1 },
      { text: 'ช่วงเวลา', exact: true, tag: 'button', n: 2 },
      { text: 'ตรวจตั้งแต่เริ่มใช้งาน', tag: 'button', n: 3 },
      { text: 'กราฟ', exact: true, tag: 'button', n: 4, side: 'bl' },
      { text: 'ตุลาคม 2569', exact: true, tag: 'span, div', n: 5, side: 'tr' },
      { text: 'Export CSV', tag: 'button', n: 6 },
      { text: 'พิมพ์ / PDF', tag: 'button', n: 7 },
    ] },
  { id: 'report-executive', path: 'report/executive',
    marks: [
      { text: 'ภาพรวม', exact: true, tag: 'button', n: 1 },
      { text: 'งานค้างที่ต้องดำเนินการตอนนี้', tag: 'div', n: 2, card: true },
      { text: 'พนักงานทั้งหมด', tag: 'div, span', n: 3, card: true },
      { text: 'ตุลาคม 2569', exact: true, tag: 'span, div', n: 4, side: 'l' },
      { text: 'Export CSV', tag: 'button', n: 5 },
      { text: 'ข้อความไลน์', tag: 'button', n: 6 },
    ] },
  { id: 'report-employee', path: 'report/employee',
    marks: [
      { text: 'ตุลาคม 2569', exact: true, tag: 'span, div', n: 1, side: 'l' },
      { selector: 'input[placeholder*="ค้นหา"]', n: 2, side: 'l' },
      { text: 'กราฟ', exact: true, tag: 'button', n: 3 },
      { text: 'OT', exact: true, tag: 'button, a', n: 4 },
      { text: 'ขอเอกสาร HR', tag: 'button, a', n: 5 },
      { text: 'Export CSV', tag: 'button', n: 6 },
      { text: 'ค่าปรับ (฿)', tag: 'th, div', n: 7 },
    ] },
  { id: 'audit-log', path: 'audit-log',
    marks: [
      { text: 'กิจกรรมพนักงาน', exact: true, tag: 'button', n: 1 },
      { text: 'การกระทำของแอดมิน', tag: 'button', n: 2 },
      { selector: 'input[placeholder*="ค้นหา"]', n: 3, side: 'l' },
      { selector: 'select', nth: 0, n: 4 },
      { selector: 'select', nth: 1, n: 5 },
      { selector: 'select', nth: 2, n: 6, side: 'tr' },
      { text: 'เพิ่มพนักงาน', exact: true, tag: 'span', n: 7 },
    ] },
  { id: 'audit-admin', path: 'audit-log', setup: async (p, { clickText, sleep }) => { await clickText(p, 'การกระทำของแอดมิน', 'button'); await sleep(1500) } },
]
